// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQydYBtUyMChHo-EF5dnvj6AqDLpMd9H8',
    appId: '1:95734214824:web:6450fdc04fd4418542129d',
    messagingSenderId: '95734214824',
    projectId: 'chat-6cfd1',
    authDomain: 'chat-6cfd1.firebaseapp.com',
    storageBucket: 'chat-6cfd1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7qnq-XUqVXr5ar4Jxj4nKqYHv3HIYZw0',
    appId: '1:95734214824:android:0dea1251ca644f7442129d',
    messagingSenderId: '95734214824',
    projectId: 'chat-6cfd1',
    storageBucket: 'chat-6cfd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr5vxuMmNhC5AdT4xUWJs9fXQ_qjEB9Wo',
    appId: '1:95734214824:ios:b2b1585cff7ae43542129d',
    messagingSenderId: '95734214824',
    projectId: 'chat-6cfd1',
    storageBucket: 'chat-6cfd1.appspot.com',
    iosClientId: '95734214824-g6iblk2ru1g3hp2kvqi1lljupinqlufj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr5vxuMmNhC5AdT4xUWJs9fXQ_qjEB9Wo',
    appId: '1:95734214824:ios:948a4d11f6b9360b42129d',
    messagingSenderId: '95734214824',
    projectId: 'chat-6cfd1',
    storageBucket: 'chat-6cfd1.appspot.com',
    iosClientId: '95734214824-oc8ppjubflammvt7cegr07r8s5qsf47k.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
